spring:
  application:
    name: men-spring-nacos-service

server:
  port: 38080

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 10.168.1.199:8848
        #namespace: 39e1e969-15f9-46d2-832d-fa052da55377
        #group: mall-user
#        cluster-name: BJ